services:
  app:
    build: .
    ports:
      - "8000:80"
    environment:
      DATABASE_URL: "mysql://root:root@db:3306/gaming_association?serverVersion=8.0&charset=utf8mb4"
      APP_ENV: dev
      APP_SECRET: "les-eternels-secret-key-dev"
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gaming_association
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db

volumes:
  mysql_data:
